name: Deploy to CapRover

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to CapRover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: '${{ secrets.CAPROVER_SERVER }}'
        app: '${{ secrets.APP_NAME }}'
        token: '${{ secrets.APP_TOKEN }}'
